# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-system-monitor-nvidia',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-system-monitor-nvidia',
                'lib_path': 'cjm_system_monitor_nvidia'},
  'syms': {}}
