"""Metadata introspection for the NVIDIA monitor plugin used by cjm-ctl to generate the registration manifest"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto #0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb #18c0f5b9
import os
import sys
from typing import Dict, Any
from . import __version__

# %% ../nbs/meta.ipynb #0cfe3c89
def get_plugin_metadata() -> Dict[str, Any]:  # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    # Fallback base path (current behavior for backward compatibility)
    base_path = os.path.dirname(os.path.dirname(sys.executable))
    
    # Use CJM config if available, else fallback to env-relative paths
    cjm_data_dir = os.environ.get("CJM_DATA_DIR")
    
    # Plugin data directory
    plugin_name = "cjm-system-monitor-nvidia"
    if cjm_data_dir:
        data_dir = os.path.join(cjm_data_dir, plugin_name)
    else:
        data_dir = os.path.join(base_path, "data")
    
    db_path = os.path.join(data_dir, "nvidia_sysmon.db")
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)
    
    return {
        "name": plugin_name,
        "version": __version__,
        "type": "infrastructure",
        "category": "system_monitor",
        "interface": "cjm_infra_plugin_system.plugin_interface.MonitorPlugin",
        
        "module": "cjm_system_monitor_nvidia.plugin",
        "class": "NvidiaMonitorPlugin",
        
        # Absolute path to this environment's Python interpreter
        "python_path": sys.executable,

        "db_path": db_path,
        
        # This plugin monitors GPUs but doesn't require GPU resources itself
        "resources": {
            "requires_gpu": False,
            "min_gpu_vram_mb": 0,
            "min_system_ram_mb": 128
        },
        
        "env_vars": {}
    }
