"""Metadata introspection for the NVIDIA monitor plugin used by cjm-ctl to generate the registration manifest"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto 0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb 2
import sys
from typing import Dict, Any

# %% ../nbs/meta.ipynb 4
def get_plugin_metadata() -> Dict[str, Any]:  # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    return {
        "name": "cjm-system-monitor-nvidia",
        "version": "1.0.0",
        "type": "infrastructure",
        "category": "system_monitor",
        "interface": "cjm_infra_plugin_system.plugin_interface.MonitorPlugin",
        
        "module": "cjm_system_monitor_nvidia.plugin",
        "class": "NvidiaMonitorPlugin",
        
        # Absolute path to this environment's Python interpreter
        "python_path": sys.executable,
        
        # This plugin monitors GPUs but doesn't require GPU resources itself
        "resources": {
            "requires_gpu": False,
            "min_gpu_vram_mb": 0,
            "min_system_ram_mb": 128
        },
        
        "env_vars": {}
    }
