"""Capability implementation for NVIDIA GPU monitoring using nvitop

Docs: https://cj-mills.github.io/cjm-capability-monitor-nvidiacapability.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/capability.ipynb.

# %% auto #0
__all__ = ['NvidiaMonitorCapability']

# %% ../nbs/capability.ipynb #44b21fb4
import logging
import psutil
import subprocess
from typing import Any, Dict, List, Optional

# Stage 8 (Option C / PILLAR 1c): the monitor re-bases onto ToolCapability. It is
# consumed through the substrate's NATIVE-DISPATCH channel -- get_system_status
# feeds resource-derived admission; list_processes feeds GPU subtree attribution
# -- so there is NO task adapter (live telemetry has no cacheable,
# content-addressable result). The dissolving cjm-infra-capability-system
# (MonitorCapability ABC + its DTOs) is replaced by ToolCapability + the data nouns
# in cjm-capability-primitives. get_plugin_metadata is gone -- name/version
# derive from importlib.metadata; there is no persistence (no db_path).
from cjm_substrate.core.capability import ToolCapability
from cjm_capability_primitives.monitoring import SystemStats, ProcessStats

# %% ../nbs/capability.ipynb #374d739a
class NvidiaMonitorCapability(ToolCapability):
    """NVIDIA System Monitor using nvitop (a pure-telemetry ToolCapability)."""

    def __init__(self):
        """Initialize the NVIDIA monitor capability."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config = {}

    @property
    def name(self) -> str:  # Tool identity, derived from the installed distribution (PILLAR 1c)
        """Get the tool name (the installed distribution name)."""
        from importlib.metadata import metadata, packages_distributions
        # `__package__` is None in a notebook/__main__ context, so guard the
        # derivation with the known package module name.
        pkg = __package__ or "cjm_capability_monitor_nvidia"
        dist = (packages_distributions().get(pkg) or [pkg.replace("_", "-")])[0]
        return metadata(dist)["Name"]

    @property
    def version(self) -> str:  # Tool version
        """Get the tool version string."""
        from cjm_capability_monitor_nvidia import __version__
        return __version__

    def initialize(
        self,
        config: Optional[Dict[str, Any]] = None  # Configuration dictionary
    ) -> None:
        """Initialize or reconfigure the capability."""
        self.config = config or {}
        # SG-40: prime psutil cpu_percent so the first get_system_status()
        # returns a real utilization delta, not 0.0 (psutil.cpu_percent()
        # yields 0.0 on its first per-process invocation).
        psutil.cpu_percent(interval=None)
        self.logger.info("NvidiaMonitor initialized")

    def get_config_schema(self) -> Dict[str, Any]:  # JSON Schema
        """Return JSON Schema for configuration."""
        return {}  # No config needed for monitoring

    def get_current_config(self) -> Dict[str, Any]:  # Current config
        """Return current configuration."""
        return self.config



    def _get_gpu_info_internal(self) -> Dict[str, Any]:  # Raw GPU data
        """Check for GPU availability and get info using nvitop."""
        gpu_info = {'available': False, 'type': 'None', 'details': {}, 'processes': []}
        
        try:
            import nvitop
            from nvitop import Device, GpuProcess, NA

            devices = Device.all()
            if devices:
                gpu_info['available'] = True
                gpu_info['type'] = 'NVIDIA'

                for i, device in enumerate(devices):
                    # Memory
                    mem_total = device.memory_total()
                    mem_used = device.memory_used()
                    mem_free = device.memory_free()
                    
                    # Convert NA to 0
                    if mem_total == NA: mem_total = 0
                    if mem_used == NA: mem_used = 0
                    if mem_free == NA: mem_free = 0

                    gpu_info['details'][f'gpu_{i}'] = {
                        'name': device.name(),
                        'memory_total': mem_total // (1024**2),
                        'memory_used': mem_used // (1024**2),
                        'memory_free': mem_free // (1024**2),
                        'utilization': device.gpu_utilization() if device.gpu_utilization() != NA else 0
                    }

                    # Per-process GPU memory
                    try:
                        for proc in device.processes().values():
                            proc_gpu_mem = proc.gpu_memory()
                            gpu_info['processes'].append({
                                'pid': proc.pid,
                                'gpu_index': i,
                                'gpu_memory_mb': proc_gpu_mem // (1024**2) if proc_gpu_mem != NA else 0,
                                'command': proc.command()[:120] if hasattr(proc, 'command') else '',
                            })
                    except Exception:
                        pass  # Process may have exited during enumeration

        except ImportError:
            # nvitop not available, fallback to nvidia-smi
            try:
                result = subprocess.run(
                    ['nvidia-smi', '--query-gpu=name,memory.total,memory.used,memory.free,utilization.gpu',
                     '--format=csv,noheader,nounits'],
                    capture_output=True, text=True, timeout=2
                )
                if result.returncode == 0:
                    lines = result.stdout.strip().split('\n')
                    for i, line in enumerate(lines):
                        parts = [p.strip() for p in line.split(',')]
                        if len(parts) >= 5:
                            gpu_info['available'] = True
                            gpu_info['type'] = 'NVIDIA'
                            gpu_info['details'][f'gpu_{i}'] = {
                                'name': parts[0],
                                'memory_total': int(float(parts[1])) if parts[1] and parts[1] != 'N/A' else 0,
                                'memory_used': int(float(parts[2])) if parts[2] and parts[2] != 'N/A' else 0,
                                'memory_free': int(float(parts[3])) if parts[3] and parts[3] != 'N/A' else 0,
                                'utilization': int(float(parts[4])) if parts[4] and parts[4] != 'N/A' else 0,
                            }

                # Per-process GPU memory via nvidia-smi
                try:
                    proc_result = subprocess.run(
                        ['nvidia-smi', '--query-compute-apps=pid,gpu_bus_id,used_memory',
                         '--format=csv,noheader,nounits'],
                        capture_output=True, text=True, timeout=2
                    )
                    if proc_result.returncode == 0 and proc_result.stdout.strip():
                        for line in proc_result.stdout.strip().split('\n'):
                            parts = [p.strip() for p in line.split(',')]
                            if len(parts) >= 3 and parts[0].isdigit():
                                gpu_info['processes'].append({
                                    'pid': int(parts[0]),
                                    'gpu_index': 0,  # Simplified; bus_id could map to index
                                    'gpu_memory_mb': int(float(parts[2])) if parts[2] and parts[2] != 'N/A' else 0,
                                    'command': '',
                                })
                except (subprocess.TimeoutExpired, FileNotFoundError, Exception):
                    pass

            except (subprocess.TimeoutExpired, FileNotFoundError, Exception):
                pass
        except Exception as e:
            self.logger.warning(f"Error checking GPU: {e}")

        return gpu_info

    def get_system_status(self) -> SystemStats:  # Current system telemetry
        """Collect host CPU/RAM + aggregated GPU stats as a typed SystemStats.

        Per-process GPU usage is exposed separately via `list_processes()`. This
        is the native-dispatch surface the substrate's `_get_global_stats` calls
        for resource-derived admission (`MonitorToolProtocol`).
        """
        # 1. Get Host CPU/RAM (psutil)
        vm = psutil.virtual_memory()

        # 2. Get GPU Data
        gpu_raw = self._get_gpu_info_internal()

        # 3. Aggregate GPU Stats for the Scheduler
        total_vram_free = 0
        total_vram_total = 0
        total_vram_used = 0
        max_load = 0

        if gpu_raw['available']:
            for key, det in gpu_raw['details'].items():
                total_vram_free += det.get('memory_free', 0)
                total_vram_total += det.get('memory_total', 0)
                total_vram_used += det.get('memory_used', 0)
                max_load = max(max_load, det.get('utilization', 0))

        # 4. Return Standardized Object
        return SystemStats(
            cpu_percent=psutil.cpu_percent(),
            memory_used_mb=vm.used / (1024**2),
            memory_total_mb=vm.total / (1024**2),
            memory_available_mb=vm.available / (1024**2),
            gpu_type=gpu_raw['type'],
            gpu_free_memory_mb=float(total_vram_free),
            gpu_total_memory_mb=float(total_vram_total),
            gpu_used_memory_mb=float(total_vram_used),
            gpu_load_percent=float(max_load),
        )

    def list_processes(self) -> List[ProcessStats]:  # Per-process GPU usage
        """Per-process GPU memory usage as typed ProcessStats.

        Sources the same nvitop/nvidia-smi enumeration `get_system_status` uses;
        returns `[]` when there is no GPU or no per-process attribution available.
        The substrate's GPU subtree attribution intersects these PIDs with the
        worker's process tree (`attribute_gpu_to_worker_subtree`).
        """
        gpu_raw = self._get_gpu_info_internal()
        return [
            ProcessStats(
                pid=int(p.get('pid', 0)),
                gpu_index=int(p.get('gpu_index', -1)),
                gpu_memory_mb=float(p.get('gpu_memory_mb', 0.0)),
                command=p.get('command', ''),
            )
            for p in gpu_raw.get('processes', [])
        ]
